Update online games controller and templates
MahjongPantheon/Rheda pull request #45
Opened 2017-06-23 14:38 UTC by Nihisil

2017-06-25 20:59 UTC, ctizen requested changes

2017-06-25 20:59 UTC, ctizen commented on src/controllers/AddOnlineGame.php
> +                $link = '';
Кажется это лишнее. И выше в условии тогда лучше $link на пустоту проверять. И в метод передавать тоже $link. Короче, чето вообще странно тут вышло

2017-06-25 20:59 UTC, ctizen commented on src/templates/MobileAddOnlineGame.handlebars
> +</div>
А вот это еще вопрос кстати, нужна ли страница добавления для мобилок. Возможно ли из мобильного клиента тенхи получить ссылку на реплей? Если да, тогда наверное действительно это имеет смысл.

2017-06-26 03:24 UTC, Nihisil commented on src/templates/MobileAddOnlineGame.handlebars
> +</div>
Насчет мобильного клиента не уверен, но если играть с телефона в web версию через браузер, то получить реплей точно можно

2017-06-27 10:45 UTC, ctizen approved these changes

2017-07-09 19:57 UTC, ctizen commented
@Nihisil не помню говорили мы уже про это или нет, но на будущее - давай будем делать rebase для обновления веток, а не подмерживать мастер.

2017-07-09 19:57 UTC, merged